\c psql_db;

INSERT INTO planets (name, type, planet_order, sun_distance, radius, day_length, year_length, moons, description, nasa_link, img_src, is_primary) VALUES

('Mercury', 'Terrestrial', 1, '36 million miles (58 million kilometers)', '1,516 miles (2,440 kilometers)', 'about 176 Earth days', '88 Earth days', 0, 'Mercury is the smallest planet in the Solar System and the closest to the Sun. Its orbit around the Sun takes 87.97 Earth days, the shortest of all the Sun-s planets.', 'https://solarsystem.nasa.gov/planets/mercury/', 'https://upload.wikimedia.org/wikipedia/commons/6/65/Colors_of_the_Innermost_Planet_2.jpg', true),
('Venus', 'Terrestrial', 2, '67 million miles (108 million kilometers)', '3,760 miles (6,050 kilometers)', '243 Earth days', '225 Earth days', 0, 'Venus is the second planet from the Sun. As the brightest natural object in Earth-s night sky after the Moon, Venus can cast shadows and can be visible to the naked eye in broad daylight.', 'https://solarsystem.nasa.gov/planets/venus/', 'https://solarsystem.nasa.gov/rails/active_storage/disk/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaDdDVG9JYTJWNVNTSXBPVE5sTkdFNE9UZ3RPVE0zTWkwME5tUmxMV0psT1RJdFpUSTRNR0l6TmprME16QmlCam9HUlZRNkVHUnBjM0J2YzJsMGFXOXVTU0k5YVc1c2FXNWxPeUJtYVd4bGJtRnRaVDBpVm1WdWRYTXVhbkJuSWpzZ1ptbHNaVzVoYldVcVBWVlVSaTA0SnlkV1pXNTFjeTVxY0djR093WlVPaEZqYjI1MFpXNTBYM1I1Y0dWSklnOXBiV0ZuWlM5cWNHVm5CanNHVkRvUmMyVnlkbWxqWlY5dVlXMWxPZ3BzYjJOaGJBPT0iLCJleHAiOm51bGwsInB1ciI6ImJsb2Jfa2V5In19--ced13bd6c8fc10deb394b681ac9fe5e6076fc906/Venus.jpg', true),
('Earth', 'Terrestrial', 3, '93 million miles (150 million kilometers)', '3,959 miles (6,371 kilometers)', '23.9 hours', '365.25 days', 1, 'Earth is the third planet from the Sun and the only astronomical object known to harbor life. While large amounts of water can be found throughout the Solar System, only Earth sustains liquid surface water. About 71% of Earth-s surface is made up of the ocean, dwarfing Earth-s polar ice, lakes, and rivers.', 'https://solarsystem.nasa.gov/planets/earth/', 'https://upload.wikimedia.org/wikipedia/commons/c/cb/The_Blue_Marble_%28remastered%29.jpg', true),
('Mars', 'Terrestrial', 4, '142 million miles (228 million kilometers)', '2,106 miles (3,390 kilometers)', '24.6 hours', '687 Earth days', 2, 'Mars is the fourth planet from the Sun and the second-smallest planet in the Solar System, being larger than only Mercury. In English, Mars is often called the Red Planet.', 'https://solarsystem.nasa.gov/planets/mars/', 'https://f4.bcbits.com/img/0023073011_10.jpg', true),
('Jupiter', 'Gas Giant', 5, '484 million miles (778 million kilometers)', '43,440.7 miles (69,911 kilometers)', '9.93 hours', '11.86 Earth Years (4,333 Earth days)', 80, 'Jupiter is the fifth planet from the Sun and the largest in the Solar System. It is a gas giant with a mass more than two and a half times that of all the other planets in the Solar System combined, but slightly less than one-thousandth the mass of the Sun.', 'https://solarsystem.nasa.gov/planets/jupiter/', 'https://upload.wikimedia.org/wikipedia/commons/8/84/Hubble_Visible_View_of_Jupiter.jpg', true),
('Saturn', 'Gas Giant', 6, '886 million miles (1.4 billion kilometers)', '36,183.7 miles (58,232 kilometers)', '10.7 hours', '29 Earth years', 83, 'Saturn is the sixth planet from the Sun and the second-largest in the Solar System, after Jupiter. It is a gas giant with an average radius of about nine and a half times that of Earth. It has only one-eighth the average density of Earth; however, with its larger volume, Saturn is over 95 times more massive.', 'https://solarsystem.nasa.gov/planets/saturn/', 'https://upload.wikimedia.org/wikipedia/commons/c/c7/Saturn_during_Equinox.jpg', true),
('Uranus', 'Ice Giant', 7, '1.8 billion miles (2.9 billion kilometers)', '15,759.2 miles (25,362 kilometers)', '17 hours 14 minutes', '84 Earth years', 27, 'Uranus is the seventh planet from the Sun. It has the third-largest planetary radius and fourth-largest planetary mass in the Solar System.', 'https://solarsystem.nasa.gov/planets/uranus/', 'https://solarsystem.nasa.gov/rails/active_storage/disk/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaDdDVG9JYTJWNVNTSXBZamxqTWpkbVlqZ3RPVEUyTnkwMFpqSmhMVGcwWVdFdE1EZGtZVE5sTTJWa05URTFCam9HUlZRNkVHUnBjM0J2YzJsMGFXOXVTU0pEYVc1c2FXNWxPeUJtYVd4bGJtRnRaVDBpVUVsQk1UZ3hPREl1YW5Cbklqc2dabWxzWlc1aGJXVXFQVlZVUmkwNEp5ZFFTVUV4T0RFNE1pNXFjR2NHT3daVU9oRmpiMjUwWlc1MFgzUjVjR1ZKSWc5cGJXRm5aUzlxY0dWbkJqc0dWRG9SYzJWeWRtbGpaVjl1WVcxbE9ncHNiMk5oYkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9rZXkifX0=--4c59d9d3b4edeb2395c799e8b5a6fd8778ab45f0/PIA18182.jpg', true),
('Neptune', 'Ice Giant', 8, '2.8 billion miles (4.5 billion kilometers)', '15,299.4 miles (24,622 kilometers)', '16 hours', '165 Earth years', 14, 'Neptune is the eighth and farthest-known Solar planet from the Sun. In the Solar System, it is the fourth-largest planet by diameter, the third-most-massive planet, and the densest giant planet. It is 17 times the mass of Earth, and slightly more massive than its near-twin Uranus.', 'https://solarsystem.nasa.gov/planets/neptune/', 'https://solarsystem.nasa.gov/rails/active_storage/disk/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaDdDVG9JYTJWNVNTSXBZMlE1TVdRd05HSXRPV016WmkwMFpqUmpMVGhqWVRBdFpqazFPVE0wTjJNeVpEQTJCam9HUlZRNkVHUnBjM0J2YzJsMGFXOXVTU0pEYVc1c2FXNWxPeUJtYVd4bGJtRnRaVDBpVUVsQk1ERTBPVEl1YW5Cbklqc2dabWxzWlc1aGJXVXFQVlZVUmkwNEp5ZFFTVUV3TVRRNU1pNXFjR2NHT3daVU9oRmpiMjUwWlc1MFgzUjVjR1ZKSWc5cGJXRm5aUzlxY0dWbkJqc0dWRG9SYzJWeWRtbGpaVjl1WVcxbE9ncHNiMk5oYkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9rZXkifX0=--4d8d92b59136a1829406d82824b488ddf7ada8d4/PIA01492.jpg', true),
('Pluto', 'Dwarf Planet', 9, '3.67 billion miles (5.91 billion kilometers)', '715 miles (1,151 kilometers)', '153 hours', '248 Earth years', 5, 'Pluto is a complex and mysterious world with mountains, valleys, plains, craters, and maybe glaciers. Discovered in 1930, Pluto was long considered our solar system-s ninth planet. But after the discovery of similar intriguing worlds deeper in the distant Kuiper Belt, icy Pluto was reclassified as a dwarf planet.', 'https://solarsystem.nasa.gov/planets/dwarf-planets/pluto/', 'https://solarsystem.nasa.gov/rails/active_storage/disk/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaDdDVG9JYTJWNVNTSXBOVGMwWlRsa1lURXRZekkzTnkwME1qQXhMVGxqTmpjdE1tSTFNRFpqWlRJellqWXdCam9HUlZRNkVHUnBjM0J2YzJsMGFXOXVTU0o5YVc1c2FXNWxPeUJtYVd4bGJtRnRaVDBpWTNKdmNGOXdYMk52Ykc5eU1sOWxibWhoYm1ObFpGOXlaV3hsWVhObFgyUmxkR0ZwYkM1cWNHY2lPeUJtYVd4bGJtRnRaU285VlZSR0xUZ25KMk55YjNCZmNGOWpiMnh2Y2pKZlpXNW9ZVzVqWldSZmNtVnNaV0Z6WlY5a1pYUmhhV3d1YW5CbkJqc0dWRG9SWTI5dWRHVnVkRjkwZVhCbFNTSVBhVzFoWjJVdmFuQmxad1k3QmxRNkVYTmxjblpwWTJWZmJtRnRaVG9LYkc5allXdz0iLCJleHAiOm51bGwsInB1ciI6ImJsb2Jfa2V5In19--1d90b6f4e5485768ff0e86a84175ad461fc598fb/crop_p_color2_enhanced_release_detail.jpg', false);
